
data:
  mongodb:
    authentication-database: myfamous-app
    database: myfamous-app
    host: myfamous.com
    port: 27017
    username: myfamous
    password: myfamous@123
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
       defaultZone: http://localhost:5000/eureka
